import { Case } from "../types";

/**
 * Case 1: "The Broken Deploy"
 *
 * The team's web app broke in production Friday night.
 * Six commits went out that day. The player must find
 * which commit broke things, and who did it.
 */
const case1: Case = {
  id: "case-01",
  title: "The Broken Deploy",
  subtitle: "Friday, 11:47 PM — Production is down.",
  briefing: [
    "The on-call pager fired at 11:47 PM on a Friday.",
    "Users are reporting that every page load returns ALL user records",
    "instead of just their own. The database is buckling under load.",
    "",
    "Six commits were deployed today. One of them broke the query",
    "that filters users. Your job: find the commit, find the author,",
    "and close the case.",
    "",
    "Use git log, git show, git diff, and git blame to investigate.",
    'Type "help" for available commands.',
  ].join("\n"),
  objectives: [
    "Review the commit history with git log",
    "Find the commit that changed the database query",
    "Identify who authored the breaking change",
    "Solve the case with: solve <commit-hash>",
  ],
  files: ["src/db.ts", "src/cache.ts", "src/index.html", "package.json", "README.md"],
  commits: [
    {
      hash: "a1b2c3d",
      author: "Alice Chen",
      email: "alice@company.dev",
      date: "2024-03-15T09:14:22-05:00",
      message: "Update homepage hero section",
      files: {
        "src/index.html": {
          diff: [
            "diff --git a/src/index.html b/src/index.html",
            "index 8f3a1b2..c4d5e6f 100644",
            "--- a/src/index.html",
            "+++ b/src/index.html",
            "@@ -12,7 +12,7 @@",
            '   <section class="hero">',
            "-    <h1>Welcome to AppStack</h1>",
            '-    <p>The platform for teams.</p>',
            "+    <h1>Build faster with AppStack</h1>",
            '+    <p>Ship with confidence. Scale without limits.</p>',
            "   </section>",
          ].join("\n"),
          contentAfter: [
            "<!DOCTYPE html>",
            "<html>",
            "<head>",
            '  <meta charset="utf-8">',
            "  <title>AppStack</title>",
            '  <link rel="stylesheet" href="style.css">',
            "</head>",
            "<body>",
            '  <nav class="main-nav">',
            '    <a href="/">AppStack</a>',
            '    <a href="/docs">Docs</a>',
            "  </nav>",
            '  <section class="hero">',
            "    <h1>Build faster with AppStack</h1>",
            "    <p>Ship with confidence. Scale without limits.</p>",
            "  </section>",
            '  <script src="app.js"></script>',
            "</body>",
            "</html>",
          ],
        },
      },
    },
    {
      hash: "e4f5g6h",
      author: "Bob Martinez",
      email: "bob@company.dev",
      date: "2024-03-15T10:31:05-05:00",
      message: "Add caching layer for API responses",
      files: {
        "src/cache.ts": {
          diff: [
            "diff --git a/src/cache.ts b/src/cache.ts",
            "new file mode 100644",
            "index 0000000..a3b4c5d",
            "--- /dev/null",
            "+++ b/src/cache.ts",
            "@@ -0,0 +1,28 @@",
            "+interface CacheEntry<T> {",
            "+  data: T;",
            "+  expires: number;",
            "+}",
            "+",
            "+const store = new Map<string, CacheEntry<unknown>>();",
            "+",
            "+export function cacheGet<T>(key: string): T | null {",
            "+  const entry = store.get(key);",
            "+  if (!entry) return null;",
            "+  if (Date.now() > entry.expires) {",
            "+    store.delete(key);",
            "+    return null;",
            "+  }",
            "+  return entry.data as T;",
            "+}",
            "+",
            "+export function cacheSet<T>(key: string, data: T, ttlMs = 60000): void {",
            "+  store.set(key, {",
            "+    data,",
            "+    expires: Date.now() + ttlMs,",
            "+  });",
            "+}",
            "+",
            "+export function cacheClear(): void {",
            "+  store.clear();",
            "+}",
          ].join("\n"),
          contentAfter: [
            "interface CacheEntry<T> {",
            "  data: T;",
            "  expires: number;",
            "}",
            "",
            "const store = new Map<string, CacheEntry<unknown>>();",
            "",
            "export function cacheGet<T>(key: string): T | null {",
            "  const entry = store.get(key);",
            "  if (!entry) return null;",
            "  if (Date.now() > entry.expires) {",
            "    store.delete(key);",
            "    return null;",
            "  }",
            "  return entry.data as T;",
            "}",
            "",
            "export function cacheSet<T>(key: string, data: T, ttlMs = 60000): void {",
            "  store.set(key, {",
            "    data,",
            "    expires: Date.now() + ttlMs,",
            "  });",
            "}",
            "",
            "export function cacheClear(): void {",
            "  store.clear();",
            "}",
          ],
        },
      },
    },
    {
      hash: "i7j8k9l",
      author: "Charlie Okafor",
      email: "charlie@company.dev",
      date: "2024-03-15T11:02:48-05:00",
      message: "Fix typo in README",
      files: {
        "README.md": {
          diff: [
            "diff --git a/README.md b/README.md",
            "index 1a2b3c4..5d6e7f8 100644",
            "--- a/README.md",
            "+++ b/README.md",
            "@@ -3,7 +3,7 @@",
            " A modern web application platform.",
            " ",
            " ## Getting Started",
            "-1. Clone the repostory",
            "+1. Clone the repository",
            " 2. Run `npm install`",
            " 3. Run `npm start`",
          ].join("\n"),
          contentAfter: [
            "# AppStack",
            "",
            "A modern web application platform.",
            "",
            "## Getting Started",
            "1. Clone the repository",
            "2. Run `npm install`",
            "3. Run `npm start`",
            "",
            "## License",
            "MIT",
          ],
        },
      },
    },
    {
      hash: "m0n1o2p",
      author: "Bob Martinez",
      email: "bob@company.dev",
      date: "2024-03-15T14:22:17-05:00",
      message: "Optimize database queries",
      files: {
        "src/db.ts": {
          diff: [
            "diff --git a/src/db.ts b/src/db.ts",
            "index 9a8b7c6..d5e4f3a 100644",
            "--- a/src/db.ts",
            "+++ b/src/db.ts",
            "@@ -18,12 +18,11 @@ const pool = createPool({",
            "   max: 20,",
            " });",
            " ",
            "-export async function getActiveUsers(orgId: string) {",
            "+export async function getActiveUsers() {",
            "   const result = await pool.query(",
            "-    'SELECT id, name, email, role FROM users WHERE org_id = $1 AND active = true',",
            "-    [orgId]",
            "+    'SELECT id, name, email, role FROM users'",
            "   );",
            "   return result.rows;",
            " }",
            " ",
            " export async function getUserById(id: string) {",
          ].join("\n"),
          contentAfter: [
            "import { createPool } from 'pg';",
            "",
            "const pool = createPool({",
            "  host: process.env.DB_HOST,",
            "  port: 5432,",
            "  database: 'appstack',",
            "  user: process.env.DB_USER,",
            "  password: process.env.DB_PASS,",
            "  max: 20,",
            "});",
            "",
            "export async function getActiveUsers() {",
            "  const result = await pool.query(",
            "    'SELECT id, name, email, role FROM users'",
            "  );",
            "  return result.rows;",
            "}",
            "",
            "export async function getUserById(id: string) {",
            "  const result = await pool.query(",
            "    'SELECT id, name, email FROM users WHERE id = $1',",
            "    [id]",
            "  );",
            "  return result.rows[0];",
            "}",
            "",
            "export async function updateUser(id: string, data: Record<string, unknown>) {",
            "  const keys = Object.keys(data);",
            "  const sets = keys.map((k, i) => `${k} = $${i + 2}`).join(', ');",
            "  const values = [id, ...Object.values(data)];",
            "  await pool.query(",
            "    `UPDATE users SET ${sets} WHERE id = $1`,",
            "    values",
            "  );",
            "}",
          ],
        },
      },
    },
    {
      hash: "q3r4s5t",
      author: "Alice Chen",
      email: "alice@company.dev",
      date: "2024-03-15T16:05:33-05:00",
      message: "Update footer links",
      files: {
        "src/index.html": {
          diff: [
            "diff --git a/src/index.html b/src/index.html",
            "index c4d5e6f..7a8b9c0 100644",
            "--- a/src/index.html",
            "+++ b/src/index.html",
            "@@ -15,5 +15,9 @@",
            "     <p>Ship with confidence. Scale without limits.</p>",
            "   </section>",
            '+  <footer class="main-footer">',
            '+    <a href="/privacy">Privacy</a>',
            '+    <a href="/terms">Terms</a>',
            '+    <a href="/contact">Contact</a>',
            "+  </footer>",
            '   <script src="app.js"></script>',
            " </body>",
          ].join("\n"),
          contentAfter: [
            "<!DOCTYPE html>",
            "<html>",
            "<head>",
            '  <meta charset="utf-8">',
            "  <title>AppStack</title>",
            '  <link rel="stylesheet" href="style.css">',
            "</head>",
            "<body>",
            '  <nav class="main-nav">',
            '    <a href="/">AppStack</a>',
            '    <a href="/docs">Docs</a>',
            "  </nav>",
            '  <section class="hero">',
            "    <h1>Build faster with AppStack</h1>",
            "    <p>Ship with confidence. Scale without limits.</p>",
            "  </section>",
            '  <footer class="main-footer">',
            '    <a href="/privacy">Privacy</a>',
            '    <a href="/terms">Terms</a>',
            '    <a href="/contact">Contact</a>',
            "  </footer>",
            '  <script src="app.js"></script>',
            "</body>",
            "</html>",
          ],
        },
      },
    },
    {
      hash: "u6v7w8x",
      author: "Charlie Okafor",
      email: "charlie@company.dev",
      date: "2024-03-15T17:40:51-05:00",
      message: "Bump dependency versions",
      files: {
        "package.json": {
          diff: [
            "diff --git a/package.json b/package.json",
            "index 2b3c4d5..e6f7a8b 100644",
            "--- a/package.json",
            "+++ b/package.json",
            "@@ -8,8 +8,8 @@",
            '   "dependencies": {',
            '-    "pg": "^8.11.0",',
            '-    "express": "^4.18.2"',
            '+    "pg": "^8.13.1",',
            '+    "express": "^4.21.0"',
            "   }",
            " }",
          ].join("\n"),
          contentAfter: [
            "{",
            '  "name": "appstack",',
            '  "version": "2.4.1",',
            '  "scripts": {',
            '    "start": "node dist/server.js",',
            '    "build": "tsc",',
            '    "test": "jest"',
            "  },",
            '  "dependencies": {',
            '    "pg": "^8.13.1",',
            '    "express": "^4.21.0"',
            "  }",
            "}",
          ],
        },
      },
    },
  ],

  solutionHash: "m0n1o2p",

  clues: [
    {
      id: "log-overview",
      title: "Commit Timeline",
      description:
        "6 commits were deployed on Friday, March 15th. Three developers were active: Alice Chen, Bob Martinez, and Charlie Okafor.",
      trigger: { type: "log" },
      discovered: false,
    },
    {
      id: "db-diff",
      title: "Missing WHERE Clause",
      description:
        'Commit m0n1o2p ("Optimize database queries") removed the WHERE clause and org_id parameter from getActiveUsers(). The query now returns ALL users instead of filtering by organization.',
      trigger: { type: "diff", hash: "m0n1o2p" },
      discovered: false,
    },
    {
      id: "db-show",
      title: "The Full Picture",
      description:
        "Bob Martinez authored commit m0n1o2p at 2:22 PM. The commit message says \"Optimize database queries\" but it actually removed critical filtering logic.",
      trigger: { type: "show", hash: "m0n1o2p" },
      discovered: false,
    },
    {
      id: "db-blame",
      title: "Blame Confirmed",
      description:
        "git blame on src/db.ts confirms Bob Martinez last touched the getActiveUsers function, removing the WHERE clause that filtered by org_id and active status.",
      trigger: { type: "blame", file: "src/db.ts" },
      discovered: false,
    },
  ],

  solvedMessage: [
    "Case closed. The culprit: commit m0n1o2p by Bob Martinez.",
    "",
    'Bob\'s "Optimize database queries" commit at 2:22 PM removed the WHERE clause',
    "from getActiveUsers(), causing every page load to return the entire users table",
    "instead of filtering by organization. The database buckled under the load.",
    "",
    "Intent was likely innocent — a misguided optimization — but the result was",
    "a production outage on a Friday night. Another reminder: always review your diffs.",
  ].join("\n"),
};

export default case1;
