import { Case } from "../types";

/**
 * Case 2: "The Vanishing Feature"
 *
 * Users report search stopped working sometime in the last two weeks.
 * 12 commits in that window. Use git bisect to find the regression.
 */
const case2: Case = {
  id: "case-02",
  title: "The Vanishing Feature",
  subtitle: "Two weeks of commits. One of them killed search.",
  briefing: [
    "Users started reporting that search returns no results.",
    "Nobody noticed exactly when it broke — it was sometime in the",
    "last two weeks. There are 12 commits in that window.",
    "",
    "Diffing every commit manually would take forever.",
    "This is a job for git bisect — binary search through history",
    "to find the exact commit that introduced the regression.",
    "",
    "Start with: git bisect start",
    "Then mark HEAD as bad and the oldest commit as good.",
    'Type "help" for available commands.',
  ].join("\n"),
  objectives: [
    "Start a bisect session",
    "Mark the current state as bad (git bisect bad)",
    "Mark the oldest known-good commit",
    "Follow the bisect to find the breaking commit",
    "Examine the breaking commit to understand what went wrong",
  ],
  files: [
    "src/search.ts",
    "src/api.ts",
    "src/auth.ts",
    "src/config.ts",
    "src/index.ts",
    "src/utils.ts",
    "tests/search.test.ts",
    "package.json",
    "README.md",
  ],
  commits: [
    {
      hash: "f1a0001",
      author: "Dana Park",
      email: "dana@company.dev",
      date: "2024-03-01T10:15:00-05:00",
      message: "Add rate limiting to public API endpoints",
      files: {
        "src/api.ts": {
          diff: [
            "diff --git a/src/api.ts b/src/api.ts",
            "--- a/src/api.ts",
            "+++ b/src/api.ts",
            "@@ -5,6 +5,14 @@",
            " import { authenticate } from './auth';",
            " ",
            "+const RATE_LIMIT = 100; // requests per minute",
            "+const rateCounts = new Map<string, number>();",
            "+",
            "+function checkRateLimit(ip: string): boolean {",
            "+  const count = rateCounts.get(ip) ?? 0;",
            "+  rateCounts.set(ip, count + 1);",
            "+  return count < RATE_LIMIT;",
            "+}",
            "+",
            " app.get('/api/search', authenticate, async (req, res) => {",
          ].join("\n"),
          contentAfter: [
            "import express from 'express';",
            "import { search } from './search';",
            "import { authenticate } from './auth';",
            "",
            "const RATE_LIMIT = 100;",
            "const rateCounts = new Map<string, number>();",
            "",
            "function checkRateLimit(ip: string): boolean {",
            "  const count = rateCounts.get(ip) ?? 0;",
            "  rateCounts.set(ip, count + 1);",
            "  return count < RATE_LIMIT;",
            "}",
            "",
            "const app = express();",
            "",
            "app.get('/api/search', authenticate, async (req, res) => {",
            "  const query = req.query.q as string;",
            "  const results = await search(query, req.user.orgId);",
            "  res.json({ results });",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0002",
      author: "Eli Vance",
      email: "eli@company.dev",
      date: "2024-03-02T14:22:00-05:00",
      message: "Update auth token expiry to 24 hours",
      files: {
        "src/auth.ts": {
          diff: [
            "diff --git a/src/auth.ts b/src/auth.ts",
            "--- a/src/auth.ts",
            "+++ b/src/auth.ts",
            "@@ -8,7 +8,7 @@",
            " export function generateToken(userId: string): string {",
            "   return jwt.sign({ userId }, SECRET, {",
            "-    expiresIn: '1h',",
            "+    expiresIn: '24h',",
            "   });",
            " }",
          ].join("\n"),
          contentAfter: [
            "import jwt from 'jsonwebtoken';",
            "",
            "const SECRET = process.env.JWT_SECRET!;",
            "",
            "export function generateToken(userId: string): string {",
            "  return jwt.sign({ userId }, SECRET, {",
            "    expiresIn: '24h',",
            "  });",
            "}",
          ],
        },
      },
    },
    {
      hash: "f1a0003",
      author: "Faye Liu",
      email: "faye@company.dev",
      date: "2024-03-04T09:45:00-05:00",
      message: "Add pagination to search results",
      files: {
        "src/search.ts": {
          diff: [
            "diff --git a/src/search.ts b/src/search.ts",
            "--- a/src/search.ts",
            "+++ b/src/search.ts",
            "@@ -12,8 +12,11 @@",
            "-export async function search(query: string, orgId: string) {",
            "+export async function search(query: string, orgId: string, page = 1, limit = 20) {",
            "+  const offset = (page - 1) * limit;",
            "   const results = await db.query(",
            "-    'SELECT * FROM documents WHERE org_id = $1 AND content ILIKE $2',",
            "-    [orgId, `%${query}%`]",
            "+    'SELECT * FROM documents WHERE org_id = $1 AND content ILIKE $2 LIMIT $3 OFFSET $4',",
            "+    [orgId, `%${query}%`, limit, offset]",
            "   );",
            "   return results.rows;",
            " }",
          ].join("\n"),
          contentAfter: [
            "import { db } from './config';",
            "",
            "export async function search(query: string, orgId: string, page = 1, limit = 20) {",
            "  const offset = (page - 1) * limit;",
            "  const results = await db.query(",
            "    'SELECT * FROM documents WHERE org_id = $1 AND content ILIKE $2 LIMIT $3 OFFSET $4',",
            "    [orgId, `%${query}%`, limit, offset]",
            "  );",
            "  return results.rows;",
            "}",
          ],
        },
      },
    },
    {
      hash: "f1a0004",
      author: "Dana Park",
      email: "dana@company.dev",
      date: "2024-03-05T11:30:00-05:00",
      message: "Fix config loading for staging environment",
      files: {
        "src/config.ts": {
          diff: [
            "diff --git a/src/config.ts b/src/config.ts",
            "--- a/src/config.ts",
            "+++ b/src/config.ts",
            "@@ -3,7 +3,8 @@",
            " export const config = {",
            "-  dbHost: process.env.DB_HOST || 'localhost',",
            "+  dbHost: process.env.DB_HOST ?? 'localhost',",
            "+  dbPort: parseInt(process.env.DB_PORT ?? '5432', 10),",
            "   jwtSecret: process.env.JWT_SECRET!,",
            " };",
          ].join("\n"),
          contentAfter: [
            "import { createPool } from 'pg';",
            "",
            "export const config = {",
            "  dbHost: process.env.DB_HOST ?? 'localhost',",
            "  dbPort: parseInt(process.env.DB_PORT ?? '5432', 10),",
            "  jwtSecret: process.env.JWT_SECRET!,",
            "};",
            "",
            "export const db = createPool({",
            "  host: config.dbHost,",
            "  port: config.dbPort,",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0005",
      author: "Eli Vance",
      email: "eli@company.dev",
      date: "2024-03-06T16:00:00-05:00",
      message: "Add search result highlighting",
      files: {
        "src/utils.ts": {
          diff: [
            "diff --git a/src/utils.ts b/src/utils.ts",
            "--- a/src/utils.ts",
            "+++ b/src/utils.ts",
            "@@ -1,3 +1,15 @@",
            "+export function highlightMatches(text: string, query: string): string {",
            "+  const regex = new RegExp(`(${escapeRegex(query)})`, 'gi');",
            "+  return text.replace(regex, '<mark>$1</mark>');",
            "+}",
            "+",
            "+function escapeRegex(str: string): string {",
            "+  return str.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');",
            "+}",
            "+",
            " export function formatDate(date: Date): string {",
            "   return date.toISOString().split('T')[0];",
            " }",
          ].join("\n"),
          contentAfter: [
            "export function highlightMatches(text: string, query: string): string {",
            "  const regex = new RegExp(`(${escapeRegex(query)})`, 'gi');",
            "  return text.replace(regex, '<mark>$1</mark>');",
            "}",
            "",
            "function escapeRegex(str: string): string {",
            "  return str.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');",
            "}",
            "",
            "export function formatDate(date: Date): string {",
            "  return date.toISOString().split('T')[0];",
            "}",
          ],
        },
      },
    },
    {
      hash: "f1a0006",
      author: "Faye Liu",
      email: "faye@company.dev",
      date: "2024-03-07T10:20:00-05:00",
      message: "Update README with search API docs",
      files: {
        "README.md": {
          diff: [
            "diff --git a/README.md b/README.md",
            "--- a/README.md",
            "+++ b/README.md",
            "@@ -10,3 +10,10 @@",
            " ## License",
            " MIT",
            "+",
            "+## Search API",
            "+GET /api/search?q=<query>&page=<n>",
            "+",
            "+Returns paginated search results for the authenticated user's org.",
          ].join("\n"),
          contentAfter: [
            "# SearchApp",
            "",
            "Full-text search for your documents.",
            "",
            "## Getting Started",
            "1. npm install",
            "2. npm start",
            "",
            "## License",
            "MIT",
            "",
            "## Search API",
            "GET /api/search?q=<query>&page=<n>",
            "",
            "Returns paginated search results for the authenticated user's org.",
          ],
        },
      },
    },
    // ---- COMMIT 7: THE BAD ONE ----
    {
      hash: "f1a0007",
      author: "Eli Vance",
      email: "eli@company.dev",
      date: "2024-03-08T13:45:00-05:00",
      message: "Refactor search module for better testability",
      files: {
        "src/search.ts": {
          diff: [
            "diff --git a/src/search.ts b/src/search.ts",
            "--- a/src/search.ts",
            "+++ b/src/search.ts",
            "@@ -1,11 +1,17 @@",
            " import { db } from './config';",
            " ",
            "-export async function search(query: string, orgId: string, page = 1, limit = 20) {",
            "+interface SearchOpts {",
            "+  page?: number;",
            "+  limit?: number;",
            "+}",
            "+",
            "+export async function search(orgId: string, query: string, opts: SearchOpts = {}) {",
            "+  const { page = 1, limit = 20 } = opts;",
            "   const offset = (page - 1) * limit;",
            "   const results = await db.query(",
            "     'SELECT * FROM documents WHERE org_id = $1 AND content ILIKE $2 LIMIT $3 OFFSET $4',",
            "-    [orgId, `%${query}%`, limit, offset]",
            "+    [orgId, `%${query}%`, limit, offset]",
            "   );",
            "   return results.rows;",
            " }",
          ].join("\n"),
          contentAfter: [
            "import { db } from './config';",
            "",
            "interface SearchOpts {",
            "  page?: number;",
            "  limit?: number;",
            "}",
            "",
            "export async function search(orgId: string, query: string, opts: SearchOpts = {}) {",
            "  const { page = 1, limit = 20 } = opts;",
            "  const offset = (page - 1) * limit;",
            "  const results = await db.query(",
            "    'SELECT * FROM documents WHERE org_id = $1 AND content ILIKE $2 LIMIT $3 OFFSET $4',",
            "    [orgId, `%${query}%`, limit, offset]",
            "  );",
            "  return results.rows;",
            "}",
          ],
        },
      },
    },
    {
      hash: "f1a0008",
      author: "Dana Park",
      email: "dana@company.dev",
      date: "2024-03-09T09:10:00-05:00",
      message: "Add request logging middleware",
      files: {
        "src/api.ts": {
          diff: [
            "diff --git a/src/api.ts b/src/api.ts",
            "--- a/src/api.ts",
            "+++ b/src/api.ts",
            "@@ -13,6 +13,12 @@",
            " const app = express();",
            " ",
            "+app.use((req, res, next) => {",
            "+  const start = Date.now();",
            "+  res.on('finish', () => {",
            "+    console.log(`${req.method} ${req.path} ${res.statusCode} ${Date.now() - start}ms`);",
            "+  });",
            "+  next();",
            "+});",
            "+",
            " app.get('/api/search', authenticate, async (req, res) => {",
          ].join("\n"),
          contentAfter: [
            "import express from 'express';",
            "import { search } from './search';",
            "import { authenticate } from './auth';",
            "",
            "const app = express();",
            "",
            "app.use((req, res, next) => {",
            "  const start = Date.now();",
            "  res.on('finish', () => {",
            "    console.log(`${req.method} ${req.path} ${res.statusCode} ${Date.now() - start}ms`);",
            "  });",
            "  next();",
            "});",
            "",
            "app.get('/api/search', authenticate, async (req, res) => {",
            "  const query = req.query.q as string;",
            "  const results = await search(query, req.user.orgId);",
            "  res.json({ results });",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0009",
      author: "Faye Liu",
      email: "faye@company.dev",
      date: "2024-03-10T15:30:00-05:00",
      message: "Add search query validation",
      files: {
        "src/api.ts": {
          diff: [
            "diff --git a/src/api.ts b/src/api.ts",
            "--- a/src/api.ts",
            "+++ b/src/api.ts",
            "@@ -14,6 +14,9 @@",
            " app.get('/api/search', authenticate, async (req, res) => {",
            "   const query = req.query.q as string;",
            "+  if (!query || query.length < 2) {",
            "+    return res.status(400).json({ error: 'Query must be at least 2 characters' });",
            "+  }",
            "   const results = await search(query, req.user.orgId);",
            "   res.json({ results });",
            " });",
          ].join("\n"),
          contentAfter: [
            "import express from 'express';",
            "import { search } from './search';",
            "import { authenticate } from './auth';",
            "",
            "const app = express();",
            "",
            "app.get('/api/search', authenticate, async (req, res) => {",
            "  const query = req.query.q as string;",
            "  if (!query || query.length < 2) {",
            "    return res.status(400).json({ error: 'Query must be at least 2 characters' });",
            "  }",
            "  const results = await search(query, req.user.orgId);",
            "  res.json({ results });",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0010",
      author: "Eli Vance",
      email: "eli@company.dev",
      date: "2024-03-11T11:00:00-05:00",
      message: "Add search test suite",
      files: {
        "tests/search.test.ts": {
          diff: [
            "diff --git a/tests/search.test.ts b/tests/search.test.ts",
            "new file mode 100644",
            "--- /dev/null",
            "+++ b/tests/search.test.ts",
            "@@ -0,0 +1,18 @@",
            "+import { search } from '../src/search';",
            "+",
            "+describe('search', () => {",
            "+  it('should return results for valid query', async () => {",
            "+    const results = await search('test-org', 'hello');",
            "+    expect(results).toBeDefined();",
            "+  });",
            "+",
            "+  it('should respect pagination', async () => {",
            "+    const results = await search('test-org', 'hello', { page: 2, limit: 5 });",
            "+    expect(results).toBeDefined();",
            "+  });",
            "+",
            "+  it('should handle empty query', async () => {",
            "+    const results = await search('test-org', '');",
            "+    expect(results).toEqual([]);",
            "+  });",
            "+});",
          ].join("\n"),
          contentAfter: [
            "import { search } from '../src/search';",
            "",
            "describe('search', () => {",
            "  it('should return results for valid query', async () => {",
            "    const results = await search('test-org', 'hello');",
            "    expect(results).toBeDefined();",
            "  });",
            "",
            "  it('should respect pagination', async () => {",
            "    const results = await search('test-org', 'hello', { page: 2, limit: 5 });",
            "    expect(results).toBeDefined();",
            "  });",
            "",
            "  it('should handle empty query', async () => {",
            "    const results = await search('test-org', '');",
            "    expect(results).toEqual([]);",
            "  });",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0011",
      author: "Dana Park",
      email: "dana@company.dev",
      date: "2024-03-12T14:15:00-05:00",
      message: "Increase connection pool size for peak traffic",
      files: {
        "src/config.ts": {
          diff: [
            "diff --git a/src/config.ts b/src/config.ts",
            "--- a/src/config.ts",
            "+++ b/src/config.ts",
            "@@ -9,5 +9,6 @@",
            " export const db = createPool({",
            "   host: config.dbHost,",
            "   port: config.dbPort,",
            "+  max: 30,",
            " });",
          ].join("\n"),
          contentAfter: [
            "import { createPool } from 'pg';",
            "",
            "export const config = {",
            "  dbHost: process.env.DB_HOST ?? 'localhost',",
            "  dbPort: parseInt(process.env.DB_PORT ?? '5432', 10),",
            "  jwtSecret: process.env.JWT_SECRET!,",
            "};",
            "",
            "export const db = createPool({",
            "  host: config.dbHost,",
            "  port: config.dbPort,",
            "  max: 30,",
            "});",
          ],
        },
      },
    },
    {
      hash: "f1a0012",
      author: "Faye Liu",
      email: "faye@company.dev",
      date: "2024-03-13T17:45:00-05:00",
      message: "Update package.json scripts for CI",
      files: {
        "package.json": {
          diff: [
            "diff --git a/package.json b/package.json",
            "--- a/package.json",
            "+++ b/package.json",
            "@@ -4,7 +4,8 @@",
            '   "scripts": {',
            '     "start": "node dist/server.js",',
            '     "build": "tsc",',
            '-    "test": "jest"',
            '+    "test": "jest --coverage",',
            '+    "lint": "eslint src/"',
            "   },",
          ].join("\n"),
          contentAfter: [
            "{",
            '  "name": "searchapp",',
            '  "version": "1.5.0",',
            '  "scripts": {',
            '    "start": "node dist/server.js",',
            '    "build": "tsc",',
            '    "test": "jest --coverage",',
            '    "lint": "eslint src/"',
            "  }",
            "}",
          ],
        },
      },
    },
  ],

  solutionHash: "f1a0007",

  clues: [
    {
      id: "log-overview",
      title: "Two Weeks of History",
      description:
        "12 commits over two weeks from three developers: Dana Park, Eli Vance, and Faye Liu. Too many to check one by one — bisect is the way.",
      trigger: { type: "log" },
      discovered: false,
    },
    {
      id: "bisect-complete",
      title: "Bisect Result",
      description:
        'git bisect identified f1a0007 — Eli Vance\'s "Refactor search module for better testability" — as the first bad commit.',
      trigger: { type: "bisect-complete" },
      discovered: false,
    },
    {
      id: "search-refactor-diff",
      title: "Swapped Arguments",
      description:
        "Commit f1a0007 changed the search() function signature from (query, orgId, ...) to (orgId, query, ...). But the caller in api.ts still passes (query, orgId) — the arguments are now swapped, so search queries the wrong column.",
      trigger: { type: "diff", hash: "f1a0007" },
      discovered: false,
    },
    {
      id: "search-refactor-show",
      title: "Refactor Gone Wrong",
      description:
        'Eli Vance refactored search.ts for "better testability" but swapped the parameter order without updating the caller. The search function now receives orgId where it expects a query, returning zero results.',
      trigger: { type: "show", hash: "f1a0007" },
      discovered: false,
    },
  ],

  solvedMessage: [
    "Case closed. The culprit: commit f1a0007 by Eli Vance.",
    "",
    'Eli\'s "Refactor search module for better testability" changed the function',
    "signature of search() from (query, orgId) to (orgId, query). The refactor",
    "updated the function definition but forgot to update the caller in api.ts.",
    "",
    "The result: the search query was being passed as the org ID, and the org ID",
    "as the search query. Every search returned zero results because no documents",
    "matched the org ID as a text search.",
    "",
    "A classic refactoring trap. The fix is a one-line argument swap in the caller.",
  ].join("\n"),
};

export default case2;
